Expands env var validation in "bootstrap" script
Removed non-Starbound env vars

diff --git a/scripts/default/bootstrap b/scripts/default/bootstrap
--- a/scripts/default/bootstrap
+++ b/scripts/default/bootstrap
@@ -86,49 +86,6 @@ EOF
 }
 
 verifyVariables() {
-
-  # if [[ -n "$SERVER_DIFFICULTY" ]]; then
-  #   if [[ "$SERVER_DIFFICULTY" -lt 0 ]] || [[ "$SERVER_DIFFICULTY" -gt 4 ]]; then
-  #     error "SERVER_DIFFICULTY must be between 0 and 4 (actual: $SERVER_DIFFICULTY)"
-  #     exit 1
-  #   fi
-  # fi
-
-  # if [[ -n "$SERVER_MAP_ID" ]]; then
-  #   if [[ "$SERVER_MAP_ID" -lt 0 ]] || [[ "$SERVER_MAP_ID" -gt 2 ]]; then
-  #     error "SERVER_MAP_ID must be between 0 and 2 (actual: $SERVER_MAP_ID)"
-  #     exit 1
-  #   fi
-  # fi
-
-  # if [[ -n "$SERVER_WORLD_SIZE" ]]; then
-  #   if ! [[ "$plainsofpain_world_sizes" =~ (^| )"$SERVER_WORLD_SIZE"($| ) ]]; then
-  #     error "SERVER_WORLD_SIZE must be one of these values: $plainsofpain_world_sizes (actual: $SERVER_WORLD_SIZE)"
-  #     exit 1
-  #   fi
-  # fi
-
-  # if [[ -n "$SERVER_SLOT_COUNT" ]]; then
-  #   if [[ "$SERVER_SLOT_COUNT" -lt 1 ]] || [[ "$SERVER_SLOT_COUNT" -gt 200 ]]; then
-  #     error "SERVER_SLOT_COUNT must be between 1 and 200 (actual: $SERVER_SLOT_COUNT)"
-  #     exit 1
-  #   fi
-  # fi
-
-  # if [[ -n "$SERVER_PORT" ]]; then
-  #   if [[ "$SERVER_PORT" -lt 1 ]] || [[ "$SERVER_PORT" -gt 65535 ]]; then
-  #     error "SERVER_PORT must be between 1 and 65535 (actual: $SERVER_PORT)"
-  #     exit 1
-  #   fi
-  # fi
-
-  # if [[ -n "$SERVER_QUERYPORT" ]]; then
-  #   if [[ "$SERVER_QUERYPORT" -lt 1 ]] || [[ "$SERVER_QUERYPORT" -gt 65535 ]]; then
-  #     error "SERVER_QUERYPORT must be between 1 and 65535 (actual: $SERVER_QUERYPORT)"
-  #     exit 1
-  #   fi
-  # fi
-
   if [[ -n "$PUID" ]]; then
     if ! [[ "$PUID" =~ ^[0-9]+$ ]]; then
       error "PUID must be a valid uid (actual: $PUID)"
@@ -146,6 +103,69 @@ verifyVariables() {
   if [[ -n "$UPDATE_CHECK_PLAYERS" ]]; then
     if [[ "$UPDATE_CHECK_PLAYERS" != "true" ]] && [[ "$UPDATE_CHECK_PLAYERS" != "false" ]]; then
       error "UPDATE_CHECK_PLAYERS must be true or false (actual: $UPDATE_CHECK_PLAYERS)"
+      exit 1
+    fi
+  fi
+
+  if [[ -n "$STEAMGUARD_REQUIRED" ]]; then
+    if [[ "$STEAMGUARD_REQUIRED" != "true" ]] && [[ "$STEAMGUARD_REQUIRED" != "false" ]]; then
+      error "STEAMGUARD_REQUIRED must be true or false (actual: $STEAMGUARD_REQUIRED)"
+      exit 1
+    fi
+  fi
+
+  if [[ -n "$STEAMGUARD_TIMEOUT" ]]; then
+    # must be a non-negative integer
+    if ! [[ "$STEAMGUARD_TIMEOUT" =~ ^[0-9]+$ ]]; then
+      error "STEAMGUARD_TIMEOUT must be a valid number (actual: $STEAMGUARD_TIMEOUT)"
+      exit 1
+    fi
+
+    # cannot exceed 3600 seconds (1 hour)
+    if (( STEAMGUARD_TIMEOUT > 3600 )); then
+      error "STEAMGUARD_TIMEOUT cannot exceed 3600 seconds (1 hour) (actual: $STEAMGUARD_TIMEOUT)"
+      exit 1
+    fi
+  fi
+
+  if [[ -n "$SERVER_SLOT_COUNT" ]]; then
+    if [[ "$SERVER_SLOT_COUNT" -lt 1 ]] || [[ "$SERVER_SLOT_COUNT" -gt 200 ]]; then
+      error "SERVER_SLOT_COUNT must be between 1 and 200 (actual: $SERVER_SLOT_COUNT)"
+      exit 1
+    fi
+  fi
+
+  if [[ -n "$SERVER_PORT" ]]; then
+    if [[ "$SERVER_PORT" -lt 1 ]] || [[ "$SERVER_PORT" -gt 65535 ]]; then
+      error "SERVER_PORT must be between 1 and 65535 (actual: $SERVER_PORT)"
+      exit 1
+    fi
+  fi
+
+  if [[ -n "$SERVER_QUERYPORT" ]]; then
+    if [[ "$SERVER_QUERYPORT" -lt 1 ]] || [[ "$SERVER_QUERYPORT" -gt 65535 ]]; then
+      error "SERVER_QUERYPORT must be between 1 and 65535 (actual: $SERVER_QUERYPORT)"
+      exit 1
+    fi
+  fi
+
+  if [[ -n "$SERVER_RCON_PORT" ]]; then
+    if [[ "$SERVER_RCON_PORT" -lt 1 ]] || [[ "$SERVER_RCON_PORT" -gt 65535 ]]; then
+      error "SERVER_RCON_PORT must be between 1 and 65535 (actual: $SERVER_RCON_PORT)"
+      exit 1
+    fi
+  fi
+
+  if [[ -n "$SERVER_CHECK_ASSETS" ]]; then
+    if [[ "$SERVER_CHECK_ASSETS" != "true" ]] && [[ "$SERVER_CHECK_ASSETS" != "false" ]]; then
+      error "SERVER_CHECK_ASSETS must be true or false (actual: $SERVER_CHECK_ASSETS)"
+      exit 1
+    fi
+  fi
+
+  if [[ -n "$USE_OPENSTARBOUND" ]]; then
+    if [[ "$USE_OPENSTARBOUND" != "true" ]] && [[ "$USE_OPENSTARBOUND" != "false" ]]; then
+      error "USE_OPENSTARBOUND must be true or false (actual: $USE_OPENSTARBOUND)"
       exit 1
     fi
   fi
