Introduces a hard exit (0) to stop the container when Steam Guard authentication times out or ultimately fails (as managed by SteamCMD)
While the container 'restart' policy is overall authoritative, the early "bootstrap" process invokes a function ('steamGuardAuth') that is effectively a hard pass/fail outcome.

Consider a ;restart' policy of "unless-stopped". Steam Guard auth-n that fails/quits/times out would result in the container restarting - and repeating the process ad infinitum.

Consider a 'restart' policy of "on-failure:3". Steam Guard auth-n that fails/quits/times out would result in the container restarting - and counting against the allocated "failures" for the remainder of the lifecycle of the container (even after potential success of the Steam Guard auth-n process).

When considering either scenario, the more risk-prone outcome prevails: effectively a "silent" failure that would require intervention when noticed ("unlress-stopped") or eventually ("on-failure:3").

Introducing this hard exit for the container process at this one specific and very-early stage more effectively enforces a pass/fail constraint - and is more likely to yield an immediate response from container orchestration/alerting/admin.

diff --git a/scripts/default/common b/scripts/default/common
--- a/scripts/default/common
+++ b/scripts/default/common
@@ -122,14 +122,14 @@ steamGuardAuth() {
     info "Environment variable 'USE_STEAMGUARD' is set to 'true' - beginning interactive SteamCMD login..."
 
     if [ ! -t 0 ]; then
-      error "stdin is not interactive/TTY; cannot proceed with interactive Steam Guard login - exiting..."
-      exit 1
+      error "stdin is not interactive/TTY; cannot proceed with interactive Steam Guard login - returning..."
+      return 42
     fi
 
     # Check if Steam credentials from Docker secrets are available
     if [ ! -f "/run/secrets/steam_username" ] || [ ! -f "/run/secrets/steam_password" ]; then
       error "Missing Docker secrets: 'steam_username' and/or 'steam_password'"
-      exit 1
+      return 42
     fi
     
     # Set environment variable values for SteamCMD authentication and Steam credentials using Docker secrets
@@ -145,16 +145,18 @@ steamGuardAuth() {
         exit 0
       else
         echo \"ERROR - SteamCMD authentication failed or timed out - exiting...\"
-        exit 2
+        exit 42
       fi
     "
 
     if [ $? -ne 0 ]; then
-      error "SteamCMD authentication (as 'starbound' user) failed - exiting..."
-      exit 2
+      error "SteamCMD authentication (as 'starbound' user) failed - returning..."
+      return 42
     fi
 
   else
     info "Environment variable 'USE_STEAMGUARD' is set to 'false' - skipping..."
   fi
+
+  return 0
 }
