Extend '$install_path' when setting working directory (facilitates 'sbinit.config' to be found by the starbound_server invocation)

diff --git a/scripts/default/starbound-server b/scripts/default/starbound-server
--- a/scripts/default/starbound-server
+++ b/scripts/default/starbound-server
@@ -6,7 +6,7 @@ starbound_server_pid=-1
 timeout=60
 kill_signal=TERM
 
-cd "$install_path" || fatal "Could not cd $install_path"
+cd "$install_path/linux" || fatal "Could not cd $install_path/linux"
 starbound_server="$install_path/$starbound_binary_path"
 
 main() {
@@ -33,7 +33,7 @@ runServer() {
   export STEAM_COMPAT_DATA_PATH="$install_path/steamapps/compatdata/$steam_app_id"
 
   chmod +x "$starbound_server"
-  $starbound_server "${install_path}/starbound_server.json" & # TODO: Invoke 'sbinit.config' here (via '-bootConfig')
+  $starbound_server & # "${install_path}/starbound_server.json" #TODO: Invoke 'sbinit.config' here (via '-bootConfig')
   starbound_server_pid=$! #TODO: Determine if there are any startup args to pass to Starbound server; determine if 'starbound_server.json' needs to be 'starbound_server.config' or 'sbinit.config'
   echo $starbound_server_pid >"$starbound_server_pidfile"
 
